-- ============================================================
-- 049_pending_claims.sql
--
-- ANON-006: the cross-browser half of 0048's claim mechanism (§2). The
-- email-confirmation link normally opens in the device's system browser,
-- whose localStorage is empty, so the local attempts recorded by an
-- anonymous learner (ANON-002) travel through the server instead: they are
-- stashed here at signup, keyed by a token carried in `emailRedirectTo`, and
-- pulled back out once the confirmation callback has a real authenticated
-- session. Full design in docs/decisions/0048-anon001-claim-token.md and
-- docs/decisions/0066-anon006-pending-claims.md (this card's own choices —
-- token format, rate-limit number, payload cap).
--
-- Adds:
--   • pending_claims — one row per outstanding claim. `token_hash` is a
--     SHA-256 hex digest of a 128-bit random token generated by the create
--     route; the raw token is never stored (0048: "hashed at rest"). RLS is
--     ON with NO POLICIES and NO GRANTS to anon/authenticated — same
--     lockdown as player_ratings — because the two SECURITY DEFINER
--     functions below are the only intended access path, in both
--     directions (write on create, read+delete on claim).
--   • pending_claims_creation_log + a BEFORE INSERT rate-limit trigger,
--     same shape as feedback (026) / account_export_log (038), but keyed by
--     IP address rather than user_id — the create endpoint has no session to
--     key on.
--   • create_pending_claim(p_token_hash, p_payload, p_ip) — lazy-sweeps
--     expired rows (0048 Decision 7: no cron), validates token/payload
--     shape, rate-limits by IP, inserts. Granted to service_role ONLY, never
--     anon or authenticated: p_ip is supplied by the caller and trusted
--     verbatim for rate-limiting, so this must only be reachable from our
--     own trusted server code (the Next.js route, via the admin client),
--     never directly over PostgREST with a caller-chosen IP.
--   • claim_pending_claim(p_token_hash) — authenticated only. Deletes the
--     row on lookup (so a replay finds nothing — "consumed once" by
--     construction, not by a separate `claimed_at` flag), checks the expiry
--     it just read, and on success calls record_lesson_attempts(payload)
--     directly — pending_claims never writes lesson_attempts itself (0048
--     Decision 2). auth.uid() inside that call resolves from the caller's
--     own JWT (unaffected by this function's own SECURITY DEFINER context),
--     so the attempts land under the confirmed user, and record_lesson_
--     attempts' own can_read_lesson check still applies per element.
--
-- Run via Supabase SQL Editor, or:
--   npx supabase db push
-- ============================================================

BEGIN;

-- ── pending_claims ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pending_claims (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  token_hash TEXT        NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  payload    JSONB       NOT NULL
               CHECK (jsonb_typeof(payload) = 'array')
               CHECK (octet_length(payload::text) <= 16384),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS pending_claims_expires_idx ON pending_claims (expires_at);

ALTER TABLE pending_claims ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE pending_claims FROM PUBLIC, anon, authenticated;
-- No GRANT and no policy at all: only the two SECURITY DEFINER functions
-- below ever touch this table.


-- ── pending_claims_creation_log + per-IP rate limit ─────────────────────
CREATE TABLE IF NOT EXISTS pending_claims_creation_log (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  ip_address INET        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS pending_claims_creation_log_ip_recent_idx
  ON pending_claims_creation_log (ip_address, created_at DESC);

ALTER TABLE pending_claims_creation_log ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE pending_claims_creation_log FROM PUBLIC, anon, authenticated;

-- Creates per IP per rolling hour. Anonymous signup traffic can share an IP
-- (NAT, campus/office wifi), so this is generous next to feedback's cap (026)
-- and account export's (038) — both per-user, not per-IP.
CREATE OR REPLACE FUNCTION pending_claims_hourly_limit()
RETURNS INTEGER
LANGUAGE sql
IMMUTABLE
AS $$ SELECT 20 $$;

REVOKE ALL ON FUNCTION pending_claims_hourly_limit() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION pending_claims_enforce_rate_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_recent INTEGER;
  v_limit  INTEGER := pending_claims_hourly_limit();
BEGIN
  SELECT count(*) INTO v_recent
  FROM pending_claims_creation_log
  WHERE ip_address = NEW.ip_address
    AND created_at > NOW() - INTERVAL '1 hour';

  IF v_recent >= v_limit THEN
    RAISE EXCEPTION 'pending claim rate limit reached (% per hour)', v_limit
      USING ERRCODE = 'PT429';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS pending_claims_creation_rate_limit ON pending_claims_creation_log;
CREATE TRIGGER pending_claims_creation_rate_limit
  BEFORE INSERT ON pending_claims_creation_log
  FOR EACH ROW
  EXECUTE FUNCTION pending_claims_enforce_rate_limit();


-- ── create_pending_claim: the only writer, service_role only ───────────
CREATE OR REPLACE FUNCTION create_pending_claim(p_token_hash TEXT, p_payload JSONB, p_ip INET)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_expires_at TIMESTAMPTZ := NOW() + INTERVAL '7 days';
BEGIN
  -- Lazy sweep (0048 Decision 7): no cron, so an expired row is only ever
  -- cleared on the next creation rather than accumulating unboundedly. The
  -- claim endpoint below refuses an expired token outright regardless, so a
  -- row surviving briefly past its expiry here is inert either way.
  DELETE FROM pending_claims WHERE expires_at < NOW();

  IF p_token_hash IS NULL OR p_token_hash !~ '^[0-9a-f]{64}$' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_token');
  END IF;

  IF p_payload IS NULL OR jsonb_typeof(p_payload) <> 'array' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_payload');
  END IF;

  IF octet_length(p_payload::text) > 16384 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'payload_too_large');
  END IF;

  BEGIN
    INSERT INTO pending_claims_creation_log (ip_address) VALUES (p_ip);
  EXCEPTION WHEN SQLSTATE 'PT429' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'rate_limited');
  END;

  INSERT INTO pending_claims (token_hash, payload, expires_at)
  VALUES (p_token_hash, p_payload, v_expires_at)
  ON CONFLICT (token_hash) DO NOTHING;

  RETURN jsonb_build_object('ok', true, 'expires_at', v_expires_at);
END;
$$;

REVOKE ALL ON FUNCTION create_pending_claim(TEXT, JSONB, INET) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION create_pending_claim(TEXT, JSONB, INET) TO service_role;


-- ── claim_pending_claim: consumes the row, feeds record_lesson_attempts ─
CREATE OR REPLACE FUNCTION claim_pending_claim(p_token_hash TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_me         UUID := auth.uid();
  v_payload    JSONB;
  v_expires_at TIMESTAMPTZ;
  v_result     JSONB;
BEGIN
  IF v_me IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'unauthenticated');
  END IF;

  -- Delete on lookup: a second claim of the same token finds no row and
  -- reports not_found, which is what makes a replay a no-op rather than a
  -- separate check-then-mark-claimed step that could race.
  DELETE FROM pending_claims
  WHERE token_hash = p_token_hash
  RETURNING payload, expires_at INTO v_payload, v_expires_at;

  IF v_payload IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_found');
  END IF;

  IF v_expires_at < NOW() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'expired');
  END IF;

  v_result := record_lesson_attempts(v_payload);
  RETURN jsonb_build_object('ok', true, 'result', v_result);
END;
$$;

REVOKE ALL ON FUNCTION claim_pending_claim(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION claim_pending_claim(TEXT) TO authenticated;

COMMIT;
